version: "3"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8001:8080"
    volumes:
      - ./todo-with-clean-architecture.yml:/todo-with-clean-architecture.yml
    environment:
      SWAGGER_JSON: /todo-with-clean-architecture.yml
